### PR TITLE
Update lab6.sql

### PR DESCRIPTION
**Pull request by maxmati**

### CODE REVIEW

**Comment by tischsoic** [comment]
Proposed alternative solution is not working:
ERROR:  syntax error at or near "select"
LINE 2: (select '93', 'Matusiak Iza', ulica, miejscowosc, kod, telef...
         ^
********** Error **********

ERROR: syntax error at or near "select"
SQL state: 42601
Character: 29

**Comment by maxmati** [comment]
Did without checking you have to delete 'values' keyword:
`insert into klienci (select '93', 'Matusiak Iza', ulica, miejscowosc, kod, telefon from klienci where nazwa = 'Matusiak Edward');`

**Comment by tischsoic** [comment]
OK, You're right, I didn't checked that. :)

**Comment by zbytspokojna** [comment]
I's fixed. It also works without parentheses, but I added them for the visual aspect

**Pull request merged**
